### ISSUE TITLE
fuck this no life fucking cunt 

### ISSUE THREAD

**Issue by joshau432** [osu-monthly/osumonthly.com#2]
the future face of osumonthly.com

We're currently redesigning the complete infrastructure of the monthly. Future editions after site completions will be hosted as an interactive webpage. Currently in a work-in-progress state.

Read below for contributing guidelines!

Join our Discord for feedback and help with contributing.

Issue/PR Guidelines
First, make sure that your issue is on-topic for this repository. You should only ask practical, answerable questions based on actual problems that you face. Chatty, open-ended questions diminish the usefulness of our repository.
Before you create a new issue, please do a search in open issues to see if the issue or feature request has already been filed. If you can fix the issue yourself, open a pull request instead.

Issues that cannot be reproduced will be put in a backlog until more details are provided or a fix is found.

Feature requests as of now are on a document. Please submit there currently.

Never push directly to the repository. Always submit a pull request for staff review.

Seeking debugging help
If you are seeking debugging help ("why isn't this code working?") you must include the desired behavior, a specific problem or error and the shortest code necessary to reproduce it in the question itself. Questions without a clear problem statement are not useful to other contributors. Issues without required informations will be closed due to lack of information.

The more information you can provide, the more likely someone will be successful reproducing the issue and finding a fix.

Please avoid creating pointless discussion. Questions that are locked are only to be used by registered contributors, and should not be discussed. You can submit a suggestion or feature request through issues or use the feedback discord channel. To make this process more effective, we're asking that these include more information to help define them more clearly.

Thank you for contributing.

**Comment by jacksonisiah** [comment]
closing and locking due to spam/content.
